### ISSUE TITLE
Start doing releases

### ISSUE THREAD

**Issue by robamu** [ObKo/stm32-cmake#254]
Some of my pull requests have already causes issues for some special configurations, which I did not use when I tested these features myself. Examples are https://github.com/ObKo/stm32-cmake/issues/251 and https://github.com/ObKo/stm32-cmake/issues/240 .  Apologies to all people who had extra work because of this.

I think it might sense to start doing releases, so users can stay on an explicitely tagged older version without things breaking.
It also makes it easier to trace changes between the different releases.

I also understand that this is extra work, but I think it is worth it if there are enough users, which I think there are for this repository (seeing how quickly new issues due to PRs are reported).

**Comment by atsju** [comment]
First of all there is at least one release : [2.0](https://github.com/ObKo/stm32-cmake/releases/tag/v2.0)
People working with master are experiencing bugs due to PR side effects and this is normal process I suppose (we do not have a dev branch).

Of course we agree on the need for releases alongside with release notes.
I think we will do a release when we are in a more steady state. For the moment we are still cleaning up the backlog of PRs that were here before @Hish15 and I became official maintainers. This process takes us some time alongside of the new issues/questions.
