### ISSUE TITLE
Support more STM32 families

### ISSUE THREAD

**Issue by ted-xp** [ObKo/stm32-cmake#7]
In my project I use STM32F207 chip so I branched https://github.com/ted-xp/stm32-cmake and extended it to support 0xx and 2xx. Some minor refactoring was done too. 

The following contribution is planned:
(1) support 0xx and 2xx chip family (done already);
(2) investigate issues with cross-building from Windows (done too);
(3) support STM32 Cube peripherial library for 2xx chips.

Current result is uploaded but tested under Windows only.

I would be glad to have some preliminary feedback and discussion from stm32-cmake developers to be able to prepare code (I hope!) for future pull request.

**Comment by mgiaco** [comment]
Hello tes-xp,

Can you explain how to build on windows a little bit better - please?
I have tried it but what do you mean with "Prepare initial CMake cache contents build_settings setting paths proper for your installation"

thanks
mathias

**Comment by mgiaco** [comment]
Okay so i got it to work on windows 7
mathias

**Comment by jerryjacobs** [comment]
@mgiaco please post how you use it on windows so @ObKo could add this to the README.md

**Comment by ted-xp** [comment]
@mgiaco, sorry for not answering for so long - I'm pretty overloaded on my current job now -) I think it might be worth that you explain which steps were unclear to you so that I could explain it better in documentation (At least the words you cited were taken from my branch of @ObKo wonderful original work).

By the way, though I made some refactoring (mostly to suit my needs: using STM32F2 family and new StdPeriph releases) of the original code and made certain handy patches, I can't help feeling that the whole build method looks weird, complicated and difficult to maintain and to extend -(

Anyway my branch is currently used in production environment to build both under Windows and Linux. Though now I prefer to use https://launchpad.net/gcc-arm-embedded/ toolchain instead of CodeSourcery mentioned in documentation file.

**Comment by mgiaco** [comment]
@ted-xp and @jerryjacobs so I only use the fork from ted-xp to build a project for an STM32F1 with the latest STM Lib for the F1. I do not use the Cube stuff till now. So add a branch to my fork I named it ted_update. So I always use out of source builds with cmake so .. I added a read.me in cmsis and in stdp.. and also in the blinky. For the blinky I also added a fab file to build with fabric. That´s really nice I think you can use python fabric to cal local make stuff :-) This also works from eclipse

**Comment by mgiaco** [comment]
In the next days I will switch back to the original master from @ObKo because he updated the whole stuff to the new Cube Libs a few days ago :-).  I only use F1 and F4 devices so I can go with it I think. My goal is to build on windows for work and linux for daily test and build. So I only tried windows now. On linux I think i do not need the the cached build settings - right?

Have you already tried to build on windows with the new master from @ObKo ?

thanks 
regards 
mathias

**Comment by ObKo** [comment]
As it is discussion thread, there is some further improvements I'm planning to do:

**Comment by ObKo** [comment]
Since this issue becomes discussion thread, there is some further improvements I'm planning to done:
* CMSIS and HAL now used as sources, so projects for CMSIS and HAL is useless. In future, cmake scripts will search for sources directly in STM32CubeMX folders using STM32Cube_DIR variable.
* Script for searching Cube's HAL will support cmake's COMPONENTS for selecting required hal components as it already done in ChibiOS scripts.
* (maybe) Autogeneration of linker script and stm32f*_hal_conf.h

**Comment by spf67** [comment]
I use STM32L152RCT6 chip. Can you help me to use this project for this chip?
